/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { PlantstoreApi } from "@fern-api/plantstore";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async add(request: PlantstoreApi.AddPlantRequest): Promise<PlantstoreApi.plant.add.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/plant/"),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      body: await serializers.plant.add.Request.json({
        id: request.id,
        category: request.category,
        name: request.name,
        photoUrls: request.photoUrls,
        status: request.status,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: undefined,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 405:
          return {
            ok: false,
            error: PlantstoreApi.plant.add.Error.invalidResponseError(),
          };
      }
    }

    return {
      ok: false,
      error: PlantstoreApi.plant.add.Error._unknown(_response.error),
    };
  }

  public async find(plantId: PlantstoreApi.PlantId): Promise<PlantstoreApi.plant.find.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, `/plant/${plantId}`),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.plant.find.Response.parse(_response.body as serializers.plant.find.Response.Raw),
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 404:
          return {
            ok: false,
            error: PlantstoreApi.plant.find.Error.plantNotFoundError(),
          };
        case 400:
          return {
            ok: false,
            error: PlantstoreApi.plant.find.Error.invalidIdSuppliedError(),
          };
      }
    }

    return {
      ok: false,
      error: PlantstoreApi.plant.find.Error._unknown(_response.error),
    };
  }

  public async delete(plantId: PlantstoreApi.PlantId): Promise<PlantstoreApi.plant.delete.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, `/plant/${plantId}`),
      method: "DELETE",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
    });
    if (_response.ok) {
      return {
        ok: true,
        body: undefined,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 404:
          return {
            ok: false,
            error: PlantstoreApi.plant.delete.Error.plantNotFoundError(),
          };
        case 400:
          return {
            ok: false,
            error: PlantstoreApi.plant.delete.Error.invalidIdSuppliedError(),
          };
      }
    }

    return {
      ok: false,
      error: PlantstoreApi.plant.delete.Error._unknown(_response.error),
    };
  }
}
