/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export type Response = core.APIResponse<void, PlantStoreApi.plant.delete.Error>;
export type Error =
  | PlantStoreApi.plant.delete.Error.PlantNotFoundError
  | PlantStoreApi.plant.delete.Error.InvalidIdSuppliedError
  | PlantStoreApi.plant.delete.Error._Unknown;

export declare namespace Error {
  interface PlantNotFoundError extends _Utils {
    error: "PlantNotFoundError";
  }

  interface InvalidIdSuppliedError extends _Utils {
    error: "InvalidIdSuppliedError";
  }

  interface _Unknown extends _Utils {
    error: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: PlantStoreApi.plant.delete.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    plantNotFoundError: () => _Result;
    invalidIdSuppliedError: () => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  plantNotFoundError: (): PlantStoreApi.plant.delete.Error.PlantNotFoundError => {
    return {
      error: "PlantNotFoundError",
      _visit: function <_Result>(
        this: PlantStoreApi.plant.delete.Error.PlantNotFoundError,
        visitor: PlantStoreApi.plant.delete.Error._Visitor<_Result>
      ) {
        return PlantStoreApi.plant.delete.Error._visit(this, visitor);
      },
    };
  },

  invalidIdSuppliedError: (): PlantStoreApi.plant.delete.Error.InvalidIdSuppliedError => {
    return {
      error: "InvalidIdSuppliedError",
      _visit: function <_Result>(
        this: PlantStoreApi.plant.delete.Error.InvalidIdSuppliedError,
        visitor: PlantStoreApi.plant.delete.Error._Visitor<_Result>
      ) {
        return PlantStoreApi.plant.delete.Error._visit(this, visitor);
      },
    };
  },

  _unknown: (fetcherError: core.Fetcher.Error): PlantStoreApi.plant.delete.Error._Unknown => {
    return {
      error: undefined,
      content: fetcherError,
      _visit: function <_Result>(
        this: PlantStoreApi.plant.delete.Error._Unknown,
        visitor: PlantStoreApi.plant.delete.Error._Visitor<_Result>
      ) {
        return PlantStoreApi.plant.delete.Error._visit(this, visitor);
      },
    };
  },

  _visit: <_Result>(
    value: PlantStoreApi.plant.delete.Error,
    visitor: PlantStoreApi.plant.delete.Error._Visitor<_Result>
  ): _Result => {
    switch (value.error) {
      case "PlantNotFoundError":
        return visitor.plantNotFoundError();
      case "InvalidIdSuppliedError":
        return visitor.invalidIdSuppliedError();
      default:
        return visitor._other(value as any);
    }
  },
} as const;
