/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export type Response = core.APIResponse<PlantStoreApi.PlantOwner, PlantStoreApi.owner.add.Error>;
export type Error = PlantStoreApi.owner.add.Error.OwnerNotFoundError | PlantStoreApi.owner.add.Error._Unknown;

export declare namespace Error {
  interface OwnerNotFoundError extends _Utils {
    error: "OwnerNotFoundError";
  }

  interface _Unknown extends _Utils {
    error: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: PlantStoreApi.owner.add.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    ownerNotFoundError: () => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  ownerNotFoundError: (): PlantStoreApi.owner.add.Error.OwnerNotFoundError => {
    return {
      error: "OwnerNotFoundError",
      _visit: function <_Result>(
        this: PlantStoreApi.owner.add.Error.OwnerNotFoundError,
        visitor: PlantStoreApi.owner.add.Error._Visitor<_Result>
      ) {
        return PlantStoreApi.owner.add.Error._visit(this, visitor);
      },
    };
  },

  _unknown: (fetcherError: core.Fetcher.Error): PlantStoreApi.owner.add.Error._Unknown => {
    return {
      error: undefined,
      content: fetcherError,
      _visit: function <_Result>(
        this: PlantStoreApi.owner.add.Error._Unknown,
        visitor: PlantStoreApi.owner.add.Error._Visitor<_Result>
      ) {
        return PlantStoreApi.owner.add.Error._visit(this, visitor);
      },
    };
  },

  _visit: <_Result>(
    value: PlantStoreApi.owner.add.Error,
    visitor: PlantStoreApi.owner.add.Error._Visitor<_Result>
  ): _Result => {
    switch (value.error) {
      case "OwnerNotFoundError":
        return visitor.ownerNotFoundError();
      default:
        return visitor._other(value as any);
    }
  },
} as const;
