/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { PlantStoreApi } from "@fern-api/plantstore";

export class InvalidIdSuppliedError extends errors.PlantStoreApiError {
    constructor(body: PlantStoreApi.InvalidId) {
        super({
            message: "InvalidIdSuppliedError",
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, InvalidIdSuppliedError.prototype);
    }
}
