/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class InvalidResponseError extends errors.PlantStoreApiError {
    constructor() {
        super({
            message: "InvalidResponseError",
            statusCode: 405,
        });
        Object.setPrototypeOf(this, InvalidResponseError.prototype);
    }
}
