/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class PlantNotFoundError extends errors.PlantStoreApiError {
    constructor() {
        super({
            message: "PlantNotFoundError",
            statusCode: 404,
        });
        Object.setPrototypeOf(this, PlantNotFoundError.prototype);
    }
}
