/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export const OwnerAge: core.schemas.Schema<serializers.OwnerAge.Raw, PlantStoreApi.OwnerAge> = core.schemas.enum_([
  "child",
  "adult",
  "senior",
]);

export declare namespace OwnerAge {
  type Raw = "child" | "adult" | "senior";
}
