/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PlantstoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export const StoreEmployee: core.schemas.ObjectSchema<serializers.StoreEmployee.Raw, PlantstoreApi.StoreEmployee> =
  core.schemas
    .object({
      employeeId: core.schemas.lazy(async () => (await import("../..")).EmployeeId),
    })
    .extend(core.schemas.lazyObject(async () => (await import("../..")).StoreCustomer));

export declare namespace StoreEmployee {
  interface Raw extends serializers.StoreCustomer.Raw {
    employeeId: serializers.EmployeeId.Raw;
  }
}
