/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export const StoreCustomer: core.schemas.ObjectSchema<serializers.StoreCustomer.Raw, PlantStoreApi.StoreCustomer> =
  core.schemas.object({
    name: core.schemas.string(),
    age: core.schemas.number().optional(),
    plants: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Plant)),
    lifetimeSpend: core.schemas.property("lifetime_spend", core.schemas.number()),
    id: core.schemas.lazy(async () => (await import("../..")).OwnerId),
  });

export declare namespace StoreCustomer {
  interface Raw {
    name: string;
    age?: number | null;
    plants: serializers.Plant.Raw[];
    lifetime_spend: number;
    id: serializers.OwnerId.Raw;
  }
}
