/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class PlantStoreApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, PlantStoreApiTimeoutError.prototype);
    }
}
