/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GautamBoseSwantide } from "@fern-api/plantstore";
import * as core from "../../../core";

export const CreateTaskResponse: core.schemas.ObjectSchema<
  serializers.CreateTaskResponse.Raw,
  GautamBoseSwantide.CreateTaskResponse
> = core.schemas.object({
  status: core.schemas.string(),
  error: core.schemas.boolean().optional(),
});

export declare namespace CreateTaskResponse {
  interface Raw {
    status: string;
    error?: boolean | null;
  }
}
