/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GautamBoseSwantide } from "@fern-api/plantstore";
import * as core from "../../../core";

export const CreateSalesMetricsDashboardRequest: core.schemas.ObjectSchema<
  serializers.CreateSalesMetricsDashboardRequest.Raw,
  GautamBoseSwantide.CreateSalesMetricsDashboardRequest
> = core.schemas.object({
  dashboardName: core.schemas.string(),
  dealCurrency: core.schemas.string(),
  hubspotId: core.schemas.string(),
});

export declare namespace CreateSalesMetricsDashboardRequest {
  interface Raw {
    dashboardName: string;
    dealCurrency: string;
    hubspotId: string;
  }
}
