/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GautamBoseSwantide } from "@fern-api/plantstore";
import * as core from "../../../core";

export const RobotAccount: core.schemas.ObjectSchema<serializers.RobotAccount.Raw, GautamBoseSwantide.RobotAccount> =
  core.schemas.object({
    email: core.schemas.string(),
    verified: core.schemas.string(),
    nickName: core.schemas.string(),
    rbAccountId: core.schemas.string(),
  });

export declare namespace RobotAccount {
  interface Raw {
    email: string;
    verified: string;
    nickName: string;
    rbAccountId: string;
  }
}
