/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GautamBoseSwantide } from "@fern-api/plantstore";
import * as core from "../../../core";

export const UserData: core.schemas.ObjectSchema<serializers.UserData.Raw, GautamBoseSwantide.UserData> =
  core.schemas.object({
    users: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).User)),
    robots: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).RobotAccount)),
  });

export declare namespace UserData {
  interface Raw {
    users: serializers.User.Raw[];
    robots: serializers.RobotAccount.Raw[];
  }
}
