/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GautamBoseSwantide } from "@fern-api/plantstore";
import * as core from "../../../core";

export const User: core.schemas.ObjectSchema<serializers.User.Raw, GautamBoseSwantide.User> = core.schemas.object({
  rbAccountId: core.schemas.string(),
  hubspotId: core.schemas.string(),
  hubspotName: core.schemas.string(),
});

export declare namespace User {
  interface Raw {
    rbAccountId: string;
    hubspotId: string;
    hubspotName: string;
  }
}
