/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateTaskResponse {
  /** The status of the task, will either returun 'success' or 'error' */
  status: string;
  error?: boolean;
}
