/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GautamBoseSwantide } from "@fern-api/plantstore";

export interface UserData {
  users: GautamBoseSwantide.User[];
  robots: GautamBoseSwantide.RobotAccount[];
}
