/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantstoreApi } from "@fern-api/plantstore";

export interface StoreEmployee extends PlantstoreApi.StoreCustomer {
  employeeId: PlantstoreApi.EmployeeId;
}
