/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantstoreApi } from "@fern-api/plantstore";

export interface StoreCustomer {
  name: string;
  age?: number;
  plants: PlantstoreApi.Plant[];
  lifetimeSpend: number;
  id: PlantstoreApi.OwnerId;
}
