/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GautamBoseSwantide } from "@fern-api/plantstore";
import * as core from "../../../core";

export const Request: core.schemas.Schema<
  serializers.hubspot.createSalesMetricsDashboard.Request.Raw,
  GautamBoseSwantide.CreateSalesMetricsDashboardRequest
> = core.schemas.lazyObject(async () => (await import("../..")).CreateSalesMetricsDashboardRequest);

export declare namespace Request {
  type Raw = serializers.CreateSalesMetricsDashboardRequest.Raw;
}

export const Response: core.schemas.Schema<
  serializers.hubspot.createSalesMetricsDashboard.Response.Raw,
  GautamBoseSwantide.CreateTaskResponse
> = core.schemas.lazyObject(async () => (await import("../..")).CreateTaskResponse);

export declare namespace Response {
  type Raw = serializers.CreateTaskResponse.Raw;
}
