/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { GautamBoseSwantide } from "@fern-api/plantstore";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.hubspot.getUserData.Response.Raw, GautamBoseSwantide.UserData> =
  core.schemas.lazyObject(async () => (await import("../..")).UserData);

export declare namespace Response {
  type Raw = serializers.UserData.Raw;
}
