/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.plant.find.Response.Raw, PlantStoreApi.Plant> =
  core.schemas.lazyObject(async () => (await import("../..")).Plant);

export declare namespace Response {
  type Raw = serializers.Plant.Raw;
}
