/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../../core";

export const OwnerId: core.serialization.Schema<serializers.OwnerId.Raw, PlantStoreApi.OwnerId> =
    core.serialization.string();

export declare namespace OwnerId {
    type Raw = string;
}
