/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../../core";

export const StoreEmployee: core.serialization.ObjectSchema<
    serializers.StoreEmployee.Raw,
    PlantStoreApi.StoreEmployee
> = core.serialization
    .object({
        employeeId: core.serialization.lazy(async () => (await import("../../..")).EmployeeId),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).StoreCustomer));

export declare namespace StoreEmployee {
    interface Raw extends serializers.StoreCustomer.Raw {
        employeeId: serializers.EmployeeId.Raw;
    }
}
