/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../../core";

export const StoreCustomer: core.serialization.ObjectSchema<
    serializers.StoreCustomer.Raw,
    PlantStoreApi.StoreCustomer
> = core.serialization.object({
    name: core.serialization.string(),
    age: core.serialization.number().optional(),
    plants: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Plant)),
    lifetimeSpend: core.serialization.property("lifetime_spend", core.serialization.number()),
    id: core.serialization.lazy(async () => (await import("../../..")).OwnerId),
});

export declare namespace StoreCustomer {
    interface Raw {
        name: string;
        age?: number | null;
        plants: serializers.Plant.Raw[];
        lifetime_spend: number;
        id: serializers.OwnerId.Raw;
    }
}
