/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantStoreApi } from "@fern-api/plantstore";

export interface PlantCategory {
  id: PlantStoreApi.CategoryId;
  name: string;
}
