/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantstoreApi } from "@fern-api/plantstore";

export interface PlantCategory {
  id: PlantstoreApi.CategoryId;
  name: string;
}
