/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantstoreApi } from "@fern-api/plantstore";

export interface Plant {
  id?: PlantstoreApi.PlantId;
  category?: PlantstoreApi.PlantCategory;
  name: string;
  photoUrls: Record<string, string>;
  status?: PlantstoreApi.PlantStatus;
}
