/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../../core";

export const CategoryId: core.serialization.Schema<serializers.CategoryId.Raw, PlantStoreApi.CategoryId> =
    core.serialization.string();

export declare namespace CategoryId {
    type Raw = string;
}
