/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../../core";

export const InvalidId: core.serialization.ObjectSchema<serializers.InvalidId.Raw, PlantStoreApi.InvalidId> =
    core.serialization.object({
        id: core.serialization.lazy(async () => (await import("../../..")).PlantId),
        message: core.serialization.string(),
    });

export declare namespace InvalidId {
    interface Raw {
        id: serializers.PlantId.Raw;
        message: string;
    }
}
