/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../../core";

export const PlantCategory: core.serialization.ObjectSchema<
    serializers.PlantCategory.Raw,
    PlantStoreApi.PlantCategory
> = core.serialization.object({
    id: core.serialization.lazy(async () => (await import("../../..")).CategoryId),
    name: core.serialization.string(),
});

export declare namespace PlantCategory {
    interface Raw {
        id: serializers.CategoryId.Raw;
        name: string;
    }
}
