/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantStoreApi } from "@fern-api/plantstore";

export interface AddOwnerRequest {
  name: string;
  age: PlantStoreApi.OwnerAge;
  plants: PlantStoreApi.Plant[];
}
