/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantstoreApi } from "@fern-api/plantstore";

export interface AddOwnerRequest {
  name: string;
  age: PlantstoreApi.OwnerAge;
  plants: PlantstoreApi.Plant[];
}
