/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PlantstoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export const CategoryId: core.schemas.Schema<serializers.CategoryId.Raw, PlantstoreApi.CategoryId> =
  core.schemas.string();

export declare namespace CategoryId {
  type Raw = string;
}
