/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export const PlantCategory: core.schemas.ObjectSchema<serializers.PlantCategory.Raw, PlantStoreApi.PlantCategory> =
  core.schemas.object({
    id: core.schemas.lazy(async () => (await import("../..")).CategoryId),
    name: core.schemas.string(),
  });

export declare namespace PlantCategory {
  interface Raw {
    id: serializers.CategoryId.Raw;
    name: string;
  }
}
