/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export const Plant: core.schemas.ObjectSchema<serializers.Plant.Raw, PlantStoreApi.Plant> = core.schemas.object({
  id: core.schemas.lazy(async () => (await import("../..")).PlantId).optional(),
  category: core.schemas.lazyObject(async () => (await import("../..")).PlantCategory).optional(),
  name: core.schemas.string(),
  photoUrls: core.schemas.record(core.schemas.string(), core.schemas.string()),
  status: core.schemas.lazy(async () => (await import("../..")).PlantStatus).optional(),
});

export declare namespace Plant {
  interface Raw {
    id?: serializers.PlantId.Raw | null;
    category?: serializers.PlantCategory.Raw | null;
    name: string;
    photoUrls: Record<string, string>;
    status?: serializers.PlantStatus.Raw | null;
  }
}
