/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PlantStoreApi } from "@fern-api/plantstore";
import * as core from "../../../core";

export const PlantId: core.schemas.Schema<serializers.PlantId.Raw, PlantStoreApi.PlantId> = core.schemas.string();

export declare namespace PlantId {
  type Raw = string;
}
