/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GautamBoseSwantide } from "@fern-api/plantstore";
import * as core from "../../../core";

export type Response = core.APIResponse<GautamBoseSwantide.UserData, GautamBoseSwantide.hubspot.getUserData.Error>;
export type Error = GautamBoseSwantide.hubspot.getUserData.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: GautamBoseSwantide.hubspot.getUserData.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  _unknown: (fetcherError: core.Fetcher.Error): GautamBoseSwantide.hubspot.getUserData.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<
      GautamBoseSwantide.hubspot.getUserData.Error._Unknown,
      "_visit"
    >;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: GautamBoseSwantide.hubspot.getUserData.Error._Unknown, visitor: GautamBoseSwantide.hubspot.getUserData.Error._Visitor<_Result>) {
      return GautamBoseSwantide.hubspot.getUserData.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: GautamBoseSwantide.hubspot.getUserData.Error,
    visitor: GautamBoseSwantide.hubspot.getUserData.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      default:
        return visitor._other(value as any);
    }
  },
} as const;
