/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as OwnerClient } from "./api/resources/owner/client/Client";
import { Client as PlantClient } from "./api/resources/plant/client/Client";

export declare namespace PlantStoreApiClient {
    interface Options {
        environment?: environments.PlantStoreApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class PlantStoreApiClient {
    constructor(private readonly options: PlantStoreApiClient.Options) {}

    #owner: OwnerClient | undefined;

    public get owner(): OwnerClient {
        return (this.#owner ??= new OwnerClient(this.options));
    }

    #plant: PlantClient | undefined;

    public get plant(): PlantClient {
        return (this.#plant ??= new PlantClient(this.options));
    }
}
