/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Client as HubspotClient } from "./resources/hubspot/client/Client";

export declare namespace GautamBoseSwantideClient {
  interface Options {
    environment: string;
  }
}

export class GautamBoseSwantideClient {
  constructor(private readonly options: GautamBoseSwantideClient.Options) {}

  #hubspot: HubspotClient | undefined;

  public get hubspot(): HubspotClient {
    return (this.#hubspot ??= new HubspotClient(this.options));
  }
}
