/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PlantStoreApiEnvironment = {
  Production: "https://api.plantstore.com",
  Sandbox: "https://sandbox.plantstore.com",
} as const;

export type PlantStoreApiEnvironment =
  | typeof PlantStoreApiEnvironment.Production
  | typeof PlantStoreApiEnvironment.Sandbox;
