/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://api.plantstore.com",
  Sandbox: "https://sandbox.plantstore.com",
} as const;

export type Environment = typeof Environment.Production | typeof Environment.Sandbox;
