/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OwnerAge = "child" | "adult" | "senior";

export const OwnerAge = {
    Child: "child",
    Adult: "adult",
    Senior: "senior",
} as const;
