/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantStoreApi } from "@fern-api/plantstore";

export interface StoreCustomer {
    name: string;
    age?: number;
    plants: PlantStoreApi.Plant[];
    lifetimeSpend: number;
    id: PlantStoreApi.OwnerId;
}
