/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PlantStoreApi } from "@fern-api/plantstore";

export interface StoreEmployee extends PlantStoreApi.StoreCustomer {
    employeeId: PlantStoreApi.EmployeeId;
}
